// Generates docs/wisc3/flagged-issues.md (English, for the psychologist) from the oracle golden files and web/src/i18n/pt.ts.
// Optional hand-maintained input: data/corrections/manual-discrepancies.json (array, or {"discrepancies":[...]}) with entries
// {id, band, test, raw, appScaled, manualScaled, source, status}. The file may be absent or empty.
// Run from tests/e2e: npm run report:flagged
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { comparisonBand } from '../../../web/src/engine/format';
import { INDEX_NAMES } from '../../../web/src/engine/types';
import type { IndexName } from '../../../web/src/engine/types';
import { pt } from '../../../web/src/i18n/pt';
import { repoRoot } from '../specs/helpers/paths';

const golden = join(repoRoot, 'tools/Wisc3.Oracle/golden');
const readJson = (p: string): any => JSON.parse(readFileSync(p, 'utf8'));
const findings = readJson(join(golden, 'findings.json'));
const indices: Record<string, { sum: number; inTable: boolean; iq: number; percentile: string; ci90: number[]; ci95: number[] }[]> = readJson(join(golden, 'indices.json'));
const corrections: any[] = readJson(join(golden, 'corrections.json'));
readJson(join(golden, 'age-gate.json')); // presence check; the leak counts come from findings.gateLeak

const LABEL: Record<IndexName, string> = {
  verbal: pt['QI.Verbal'],
  realization: pt['QI.Realization'],
  completeScale: pt['QI.CompleteScale'],
  verbalComprehension: pt['QI.VerbalComprehension'],
  perceptiveOrganization: pt['QI.PerceptiveOrganization'],
  processingVelocity: pt['QI.ProcessingVelocity'],
};

const KEPT = 'Kept as-is, needs confirmation.';
const ageText = (a: number[]) => `${a[0]}y ${a[1]}m ${a[2]}d`;
const pct = (n: number, total: number) => `${((n / total) * 100).toFixed(1)}%`;

/** 5,6,7,9 -> "5-7, 9" */
function ranges(xs: number[]): string {
  const out: string[] = [];
  let i = 0;
  while (i < xs.length) {
    let j = i;
    while (j + 1 < xs.length && xs[j + 1] === xs[j] + 1) j++;
    out.push(i === j ? `${xs[i]}` : `${xs[i]}-${xs[j]}`);
    i = j + 1;
  }
  return out.join(', ') || 'none';
}

const md: string[] = [];
md.push('# WISC-III next: flagged issues', '');
md.push(
  'Generated by `npm run report:flagged` (tests/e2e) from the oracle golden files of the old calculator. The new app keeps the old behaviour for every item in sections 1-6 and 8; only the age-gate leak (section 7) is fixed. No table, label or displayed content has been changed, except the single manual-confirmed correction listed under Resolved.',
  '',
);

// 1
md.push('## 1. IQ 999 for Complete Scale sums 182-190', '');
md.push(`${KEPT} The old tables return IQ 999 for these sums; the percentile and confidence intervals are shown exactly as the old app shows them.`, '');
md.push('| Complete Scale sum | IQ | Percentile | CI 90% | CI 95% |', '|---|---|---|---|---|');
for (const r of indices.completeScale.filter((x) => findings.iq999.completeScale.includes(x.sum)))
  md.push(`| ${r.sum} | ${r.iq} | ${r.percentile} | ${r.ci90.join(' - ')} | ${r.ci95.join(' - ')} |`);
const other999 = INDEX_NAMES.filter((n) => n !== 'completeScale' && findings.iq999[n].length > 0);
md.push('', other999.length ? `Other indices with IQ 999: ${other999.join(', ')}.` : 'No other index has IQ 999 rows.', '');

// 2
md.push('## 2. Percentile 0 and 100 rows', '');
md.push(`${KEPT} These rows exist in the old tables as 0 and 100; please confirm that they are real manual values and not table placeholders.`, '');
md.push('| Index | Sums with percentile 0 | Sums with percentile 100 |', '|---|---|---|');
for (const n of INDEX_NAMES) {
  const rows: { sum: number; percentile: string }[] = findings.pct0or100[n];
  md.push(`| ${LABEL[n]} | ${ranges(rows.filter((r) => r.percentile === '0').map((r) => r.sum))} | ${ranges(rows.filter((r) => r.percentile === '100').map((r) => r.sum))} |`);
}
md.push('');

// 3
md.push('## 3. Classification bands and their displayed texts', '');
md.push(`${KEPT} Texts are shown exactly as the old app shows them (including the wording "Inferior à médio"). Please confirm whether the wording and the order match the manual.`, '');
md.push('| IQ range | Displayed text |', '|---|---|');
const bandRows: { from: number; to: number; band: string }[] = [];
for (let iq = 0; iq <= 999; iq++) {
  const b = comparisonBand(iq);
  const last = bandRows[bandRows.length - 1];
  if (last && last.band === b) last.to = iq;
  else bandRows.push({ from: iq, to: iq, band: b });
}
for (const r of bandRows) {
  const range = r.from === 0 ? `up to ${r.to}` : r.to === 999 ? `${r.from} and above` : `${r.from} - ${r.to}`;
  md.push(`| ${range} | ${pt[`QI.AverageComparison.${r.band}`]} |`);
}
md.push('');

// 4
const dc = findings.dayCountVsCalendar;
md.push('## 4. Day-count age versus calendar age', '');
md.push(
  `${KEPT} The old app computes the age as a day count added to 0001-01-01 (not the calendar difference), and the new app does the same. In ${dc.pairs} simulated date pairs the displayed age differs from the calendar age in ${dc.ageDiffersPercent}% of them, and the norm band differs in ${dc.bandDiffersPercent}%. Please confirm that the day-count rule is the intended one.`,
  '',
);
md.push('Examples where the displayed age differs (test date, birth date, day-count age, calendar age):', '');
for (const e of dc.ageExamples.slice(0, 5)) md.push(`- ${e.test}, ${e.birth}: ${ageText(e.dayCount)} versus ${ageText(e.calendar)}`);
md.push('', 'Examples where the norm band differs (test date, birth date, day-count band, calendar band):', '');
for (const e of dc.bandExamples.slice(0, 5)) md.push(`- ${e.test}, ${e.birth}: ${e.bandDayCount} (${ageText(e.dayCount)}) versus ${e.bandCalendar} (${ageText(e.calendar)})`);
md.push('');

// 5
md.push('## 5. Index sums that are not in the conversion tables', '');
md.push(`${KEPT}`, '');
md.push('The old app finds an index (IQ, percentile, CI) only for sums that exist as keys in its tables. Two situations were checked:', '');
md.push('- Sums inside the table range that are not keys (gaps): ' + (INDEX_NAMES.every((n) => findings.inRangeNonKey[n].length === 0) ? 'none found in any index.' : INDEX_NAMES.map((n) => `${LABEL[n]}: ${ranges(findings.inRangeNonKey[n])}`).join('; ') + '.'));
md.push('- Sums outside the table range (below the lowest key or above the highest): the old app silently showed another row (for example the verbal sum 0 gives IQ 155, percentile 100). The new app shows these cells as unavailable (a dash, with the hint "Soma fora da tabela de conversão") and draws no classification arrow or chart value for that index. Please confirm that "unavailable" is the right behaviour.', '');
md.push('| Index | Sums shown as unavailable in the new app | Count |', '|---|---|---|');
for (const n of INDEX_NAMES) {
  const missing = indices[n].filter((r) => !r.inTable).map((r) => r.sum);
  md.push(`| ${LABEL[n]} | ${ranges(missing)} | ${missing.length} |`);
}
md.push('');

// 6
const pv = findings.pvWithoutSymbolSearch;
md.push('## 6. Processing Speed index from Coding alone (Symbol Search omitted)', '');
md.push(
  `${KEPT} When the optional Symbol Search test is omitted, the Processing Speed sum is made from Coding alone and an index is still shown when that sum exists in the table. This happened in ${pv.count} of ${pv.scenarios} simulated cases (${pct(pv.count, pv.scenarios)}); examples (simulated case ids): ${pv.examples.join(', ')}. Decision for now: kept; to be validated with the psychologist.`,
  '',
);

// 7
const g = findings.gateLeak;
md.push('## 7. Age-gate leak (fixed)', '');
md.push(
  `Deliberately changed, needs confirmation. The supported age range is 6y 0m 0d up to (not including) 17y 0m 0d. The old gate leaked at both edges: ${g.oldSupportedBelow6y} ages below 6 years (5y 10m 0d to 5y 11m 30d) were scored with the 6y 6m band, and ${g.oldSupportedFrom17y} ages from 17y 0m 0d to 17y 2m 30d passed the gate (${g.oldSupportedFrom17yThrowing} of them crash the old app). The new app blocks all of them like any other unsupported age. Please confirm that the strict range is wanted.`,
  '',
);

// 8
md.push('## 8. Percentile number format follows the browser locale', '');
md.push(`${KEPT} The old app writes percentiles with the browser's decimal separator (for example "0,5" with a Portuguese browser, "0.5" with an English one). The new app does the same. Please confirm that this is acceptable on printed or pasted results.`, '');

// manual discrepancies (optional file)
const discPath = join(repoRoot, 'data/corrections/manual-discrepancies.json');
let disc: any[] = [];
if (existsSync(discPath)) {
  const raw = readFileSync(discPath, 'utf8').trim();
  if (raw) {
    const parsed = JSON.parse(raw);
    disc = Array.isArray(parsed) ? parsed : (parsed.discrepancies ?? []);
  }
}
const openDisc = disc.filter((d) => String(d.status ?? 'open').toLowerCase() !== 'resolved');
md.push('## Discrepancies vs printed manual (open, NOT changed)', '');
if (openDisc.length === 0) {
  md.push('None recorded.', '');
} else {
  md.push('Found while checking the norm tables against the printed manual (Table 36, Portuguese WISC-III). The app tables are NOT changed; each item needs the psychologist to confirm which value is right.', '');
  md.push('| Id | Band | Test | Raw | App scaled | Manual scaled | Source | Status |', '|---|---|---|---|---|---|---|---|');
  const cellText = (v: unknown) => String(v ?? '').replace(/\|/g, '/');
  for (const d of openDisc)
    md.push(`| ${cellText(d.id)} | ${cellText(d.band)} | ${cellText(d.test)} | ${cellText(d.raw)} | ${cellText(d.appScaled)} | ${cellText(d.manualScaled)} | ${cellText(d.source)} | ${cellText(d.status ?? 'open')} |`);
  md.push('');
}

// resolved
md.push('## Resolved', '');
const bandLabel = (band: string) => {
  const m = /^(\d+)y(\d+)m$/.exec(band);
  return m ? `${Number(m[1])}${m[2] === '06' ? ' 1/2' : ''} anos` : band;
};
for (const c of corrections) {
  const scaled = c.corrected.find((v: number | null) => v !== null);
  const range: number[] | undefined = readJson(join(repoRoot, `data/wisc3-pt/subtests/${c.band}.json`))[c.test]?.scaled?.[String(scaled)];
  md.push(
    `- ${c.id}: ${c.band} (${bandLabel(c.band)}), ${pt[`Test.${c.test}`] ?? c.test}, raw ${c.raw}: old table had no mapping (app error); now scaled ${scaled}${range ? ` (raw ${range[0]}-${range[1]})` : ''}. Source: ${c.source}; user-confirmed ${c.confirmedOn}.`,
  );
}
for (const d of disc.filter((x) => String(x.status ?? '').toLowerCase() === 'resolved'))
  md.push(`- ${d.id}: ${d.band}, ${d.test}, raw ${d.raw}: app scaled ${d.appScaled}, manual ${d.manualScaled}. Source: ${d.source}.`);
md.push('');

const out = join(repoRoot, 'docs/wisc3/flagged-issues.md');
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, md.join('\n'));
console.log(`flagged-issues: wrote ${out} (open discrepancies: ${openDisc.length})`);
